import json
import os
import subprocess
import tempfile
import re
from dataclasses import dataclass, field
from typing import Optional, List
from datetime import datetime

@dataclass
class GeminiRequest:
    prompt: str
    cwd: Optional[str] = None
    resume: bool = False
    approval_mode: str = "plan"
    system_prompt: Optional[str] = None
    timeout_sec: int = 300

@dataclass
class GeminiResult:
    ok: bool
    stdout: str
    stderr: str

def run_gemini(req: GeminiRequest) -> GeminiResult:
    exe = "gemini.cmd" if os.name == "nt" else "gemini"
    cmd = [exe, "-p", req.prompt, "--approval-mode", req.approval_mode]
    
    if req.resume:
        cmd += ["--resume", "latest"]

    env = os.environ.copy()
    tmp_sys_path = None
    if req.system_prompt:
        fd, tmp_sys_path = tempfile.mkstemp(suffix=".md", prefix="gemini_sys_")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(req.system_prompt)
        env["GEMINI_SYSTEM_MD"] = tmp_sys_path

    try:
        completed = subprocess.run(
            cmd, cwd=req.cwd, env=env, text=True, capture_output=True, timeout=req.timeout_sec, encoding="utf-8"
        )
        return GeminiResult(ok=completed.returncode == 0, stdout=completed.stdout, stderr=completed.stderr)
    finally:
        if tmp_sys_path and os.path.exists(tmp_sys_path):
            os.unlink(tmp_sys_path)

def save_handoff(folder: str, filename: str, content: str):
    path = os.path.join(folder, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"📄 Handoff 저장됨: {path}")

def pipeline(user_request: str):
    # 핸드오프 폴더 생성 (요청 기반 고유 이름)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_request = re.sub(r'[^\w\s-]', '', user_request)[:20].strip().replace(' ', '_')
    handoff_dir = os.path.join("handoffs", f"{timestamp}_{safe_request}")
    os.makedirs(handoff_dir, exist_ok=True)

    print(f"🚀 파이프라인 시작: {user_request}")
    print(f"📁 결과물 폴더: {handoff_dir}\n")

    # 단계 1: Planning
    print("Step 1: Planning...")
    p1_sys = "당신은 숙련된 소프트웨어 아키텍트입니다. 사용자의 요청을 분석하고 구현을 위한 초기 전략을 수립하세요."
    res1 = run_gemini(GeminiRequest(
        prompt=f"[Planning] 다음 요청에 대한 아키텍처 및 구현 전략을 세워줘: {user_request}",
        system_prompt=p1_sys
    ))
    if not res1.ok: return print(f"Error in Step 1: {res1.stderr}")
    save_handoff(handoff_dir, "00_planning.md", f"# 📋 Initial Planning\n\n{res1.stdout}")

    # 단계 2: Review
    print("Step 2: Review...")
    p2_sys = "당신은 까다로운 코드 리뷰어입니다. 이전 단계의 계획에서 누락된 엣지 케이스, 보안 취약점, 구조적 결함을 찾아 비판적으로 리뷰하세요."
    res2 = run_gemini(GeminiRequest(
        prompt="[Review] 이전 단계를 리뷰하고 개선이 필요한 점을 나열해줘.",
        resume=True,
        system_prompt=p2_sys
    ))
    if not res2.ok: return print(f"Error in Step 2: {res2.stderr}")
    save_handoff(handoff_dir, "01_review.md", f"# 🔍 Design Review\n\n{res2.stdout}")

    # 단계 3: Revised Planning
    print("Step 3: Revised Planning...")
    p3_sys = "당신은 아키텍트입니다. 리뷰어의 피드백을 수용하여 최종 수정된 설계안을 작성하세요."
    res3 = run_gemini(GeminiRequest(
        prompt="[Revised Planning] 리뷰 내용을 반영하여 최종 설계안을 확정해줘.",
        resume=True,
        system_prompt=p3_sys
    ))
    if not res3.ok: return print(f"Error in Step 3: {res3.stderr}")
    save_handoff(handoff_dir, "02_revised_planning.md", f"# 🏗️ Revised Architecture Design\n\n{res3.stdout}")

    # 단계 4: Todo 도출
    print("Step 4: Generating Todo...")
    p4_sys = "당신은 실무에 능한 시니어 개발자입니다. 최종 설계안을 바탕으로 즉시 실행 가능한 구체적인 Todo 리스트를 작성하세요."
    res4 = run_gemini(GeminiRequest(
        prompt="[Todo] 위 설계를 바탕으로 단계별 할 일 목록(Todo)을 작성해줘. 각 단계마다 검증 방법도 포함해.",
        resume=True,
        system_prompt=p4_sys
    ))
    if not res4.ok: return print(f"Error in Step 4: {res4.stderr}")
    save_handoff(handoff_dir, "03_todo_list.md", f"# ✅ Implementation Todo List\n\n{res4.stdout}")

    # 단계 5: Final Plan Report (취합)
    print("Step 5: Finalizing Report...")
    final_content = f"""# 📋 Project Plan & Final Report

## 1. User Request
{user_request}

## 2. Final Architecture Design
{res3.stdout}

## 3. Implementation Todo List
{res4.stdout}

---
*Generated by Gemini CLI Pipeline*
"""
    save_handoff(handoff_dir, "04_final_plan_report.md", final_content)
    
    # 루트에도 프로젝트 전체 결과로 하나 복사 (편의용)
    with open("PROJECT_PLAN.md", "w", encoding="utf-8") as f:
        f.write(final_content)
    
    print(f"\n✅ 완료! 모든 핸드오프 파일이 '{handoff_dir}'에 저장되었습니다.")

if __name__ == "__main__":
    import sys
    request = sys.argv[1] if len(sys.argv) > 1 else "yacht_game.py에 점수 기록 로그 기능을 추가해줘."
    pipeline(request)
